# -----------------------------------
# Production Stage
# -----------------------------------
FROM oven/bun:1.1.8 AS prod
WORKDIR /app

COPY bun.lockb package.json tsconfig.json ./
COPY prisma ./prisma
RUN bun install --production

COPY src ./src

CMD ["bun", "src/index.ts"]
    